### ISSUE TITLE
bundle update

### ISSUE THREAD

**Issue by jankeesvw** [80beans/nkss-rails#3]
I get this error when I try to do a bundle update:

```
Could not find gem 'nkss-rails (>= 0) ruby' in
git://github.com/80beans/nkss-rails.git (at master).
Source does not contain any versions of 'nkss-rails (>= 0) ruby'
```

I have this entry in my Gemfile, which worked before:

```
gem 'nkss-rails', github: '80beans/nkss-rails'
```

**Comment by thijsc** [comment]
We renamed this gem to bkss-rails so we could do a separate gem release, since the owner was not responding. If you use that name, or the gem from rubygems you should be fine.

**Comment by jankeesvw** [comment]
Ah, thanks for the response! Seems to work.

**Comment by jankeesvw** [comment]
Now I get another error:

```
uninitialized constant Nkss
/Users/jankeesvw/Documents/timi/timi/config/routes.rb:104:in `block in <top (required)>'
/Users/jankeesvw/Documents/timi/timi/config/routes.rb:1:in `<top (required)>'
/Users/jankeesvw/Documents/timi/timi/config/environment.rb:5:in `<top (required)>'
```

The routes.rb section:

```
mount Nkss::Engine => '/styleguides' unless Rails.env.production?
```

**Comment by jankeesvw** [comment]
It's fixed, sorry ;)

![imgres](https://f.cloud.github.com/assets/167882/1698290/0e88becc-5f3f-11e3-8c3a-b1a5a92b67ca.jpg)

**Comment by suweller** [comment]
The owners are biased towards using `slim` templates in the gem, which imho needlessly increased the number of gem dependencies. Before they change their opinion on that, this fork can not be merged.
